services:
  - type: web
    name: respisense-ml
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: FLASK_ENV
        value: production
